In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

In [3]:
arr = np.array(l)

In [4]:
type(arr)

numpy.ndarray

In [5]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [8]:
arr1 = np.array([[1,2,3], [2,3,4]])

In [9]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [10]:
arr.ndim

1

In [11]:
arr1.ndim

2

In [12]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [14]:
mat = np.matrix(l)

In [15]:
mat.ndim

2

In [16]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [17]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [19]:
np.array(mat)

array([[1, 2, 3, 4, 5]])

In [20]:
arr

array([1, 2, 3, 4, 5])

In [21]:
a = arr

In [23]:
arr[0] = 100

In [24]:
a 


array([100,   2,   3,   4,   5])

In [25]:
b = np.copy(arr)

In [26]:
b

array([100,   2,   3,   4,   5])

In [28]:
b[2] = 400

In [29]:
print(b)
print(arr)

[100   2 400   4   5]
[100   2   3   4   5]


In [32]:
np.fromfunction(lambda i,j: i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [33]:
np.fromfunction(lambda i,j: i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [36]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [44]:
iterable = (i*i for i in range(5))

In [45]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [48]:
np.fromstring('23 45 56 67', sep=' ', dtype=int)

array([23, 45, 56, 67])

In [49]:
arr.size

5

In [50]:
arr1.size

6

In [52]:
arr

array([100,   2,   3,   4,   5])

In [53]:
arr1.shape

(2, 3)

In [54]:
arr.shape

(5,)

In [55]:
arr.dtype

dtype('int32')

In [56]:
arr1.dtype


dtype('int32')

# Part 2

In [57]:
import numpy as np

In [59]:
list(np.arange(5.5, 10.5))

[5.5, 6.5, 7.5, 8.5, 9.5]

In [60]:
np.linspace(1,5, 20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [61]:
np.logspace(1,5, 10, base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [62]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [63]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [65]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [67]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [68]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [75]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [73]:
arr = np.ones((3,4))

In [74]:
arr + 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [76]:
arr*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [77]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [79]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [82]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [83]:
arr1 = np.eye(5)

In [84]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [85]:
import pandas as pd

In [87]:
pd.DataFrame(arr1, columns =['a', 'b', 'c', 'd', 'e'])

a    b    c    d    e
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [89]:
np.random.rand(2,3)

array([[0.16243947, 0.19431512, 0.68444513],
       [0.00882796, 0.85497828, 0.92601224]])

In [90]:
np.random.randn(2,3)

array([[ 1.94050634,  0.37061407, -0.70897349],
       [ 0.89904877,  0.98256194,  0.63119145]])

In [92]:
arr2 = np.random.randint(1,5, (3,4))

In [93]:
arr2

array([[3, 4, 1, 3],
       [2, 3, 4, 3],
       [3, 2, 4, 1]])

In [94]:
arr2.size

12

In [95]:
arr2.shape

(3, 4)

In [96]:
arr2.reshape(1,12)

array([[3, 4, 1, 3, 2, 3, 4, 3, 3, 2, 4, 1]])

In [98]:
arr2.reshape(6,2)

array([[3, 4],
       [1, 3],
       [2, 3],
       [4, 3],
       [3, 2],
       [4, 1]])

In [99]:
arr2.reshape(2,6)

array([[3, 4, 1, 3, 2, 3],
       [4, 3, 3, 2, 4, 1]])

In [100]:
arr2.reshape(4,3)

array([[3, 4, 1],
       [3, 2, 3],
       [4, 3, 3],
       [2, 4, 1]])

In [101]:
arr2.reshape(4, -1)

array([[3, 4, 1],
       [3, 2, 3],
       [4, 3, 3],
       [2, 4, 1]])

In [111]:
arr2.reshape(2,2,3)

array([[[3, 4, 1],
        [3, 2, 3]],

       [[4, 3, 3],
        [2, 4, 1]]])

In [118]:
arr3 = np.random.randint(1,10, (5,6))

In [119]:
arr3

array([[8, 2, 1, 1, 4, 6],
       [4, 2, 3, 7, 8, 9],
       [4, 9, 2, 8, 5, 5],
       [5, 2, 2, 1, 9, 8],
       [8, 7, 5, 8, 7, 9]])

In [120]:
arr3 >8

array([[False, False, False, False, False, False],
       [False, False, False, False, False,  True],
       [False,  True, False, False, False, False],
       [False, False, False, False,  True, False],
       [False, False, False, False, False,  True]])

In [121]:
arr3[arr3 > 8]

array([9, 9, 9, 9])

In [123]:
arr3

array([[8, 2, 1, 1, 4, 6],
       [4, 2, 3, 7, 8, 9],
       [4, 9, 2, 8, 5, 5],
       [5, 2, 2, 1, 9, 8],
       [8, 7, 5, 8, 7, 9]])

In [122]:
arr3[0]

array([8, 2, 1, 1, 4, 6])

In [125]:
arr3[0,[0,1]]

array([8, 2])

In [137]:
arr3[2:4, [2,3]]

array([[2, 8],
       [2, 1]])

In [139]:
arr4 = np.random.randint(1,3, (3,3))

arr5 = np.random.randint(1,3, (3,3))

In [140]:
arr4

array([[2, 2, 2],
       [2, 1, 1],
       [1, 2, 2]])

In [141]:
arr5

array([[2, 1, 1],
       [1, 2, 1],
       [2, 1, 1]])

In [142]:
arr4 + arr5

array([[4, 3, 3],
       [3, 3, 2],
       [3, 3, 3]])

In [143]:
arr5 - arr4

array([[ 0, -1, -1],
       [-1,  1,  0],
       [ 1, -1, -1]])

In [144]:
arr4 * arr5

array([[4, 2, 2],
       [2, 2, 1],
       [2, 2, 2]])

In [145]:
arr4@arr5  #matrix multiplication

array([[10,  8,  6],
       [ 7,  5,  4],
       [ 8,  7,  5]])

In [146]:
arr4/arr5

array([[1. , 2. , 2. ],
       [2. , 0.5, 1. ],
       [0.5, 2. , 2. ]])

In [147]:
arr4/0

C:\Users\sodiq\AppData\Local\Temp\ipykernel_22404\1674986024.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr4/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

## Numpy - Broadcasting

In [148]:
arr = np.zeros((3,4))

In [149]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [150]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [151]:
a = np.array([1,2,3,4])

In [152]:
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [153]:
b = np.array([3,4,5])

In [154]:
arr +b

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [155]:
b = np.array([[3,4,5]])

In [156]:
arr+b.T

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [157]:
b.T

array([[3],
       [4],
       [5]])

In [158]:
arr1 = arr+b.T

In [159]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [160]:
np.log(arr1)

array([[1.09861229, 1.09861229, 1.09861229, 1.09861229],
       [1.38629436, 1.38629436, 1.38629436, 1.38629436],
       [1.60943791, 1.60943791, 1.60943791, 1.60943791]])

In [161]:
np.exp(arr1)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [162]:
np.min(arr1)

3.0

In [163]:
np.max(arr1)

5.0

## PART 3:

In [164]:
import numpy as np

In [165]:
#Numpy -  Array Manipulation

In [167]:
arr = np.random.randint(1,10, (4,4))

In [168]:
arr

array([[6, 2, 7, 3],
       [1, 3, 8, 2],
       [3, 3, 6, 1],
       [1, 1, 1, 4]])

In [169]:
arr.reshape(8,2)

array([[6, 2],
       [7, 3],
       [1, 3],
       [8, 2],
       [3, 3],
       [6, 1],
       [1, 1],
       [1, 4]])

In [170]:
arr.T

array([[6, 1, 3, 1],
       [2, 3, 3, 1],
       [7, 8, 6, 1],
       [3, 2, 1, 4]])

In [171]:
arr

array([[6, 2, 7, 3],
       [1, 3, 8, 2],
       [3, 3, 6, 1],
       [1, 1, 1, 4]])

In [172]:
arr.flatten()

array([6, 2, 7, 3, 1, 3, 8, 2, 3, 3, 6, 1, 1, 1, 1, 4])

In [174]:
np.expand_dims(arr, axis=1)

array([[[6, 2, 7, 3]],

       [[1, 3, 8, 2]],

       [[3, 3, 6, 1]],

       [[1, 1, 1, 4]]])

In [175]:
np.expand_dims(arr, axis=0)

array([[[6, 2, 7, 3],
        [1, 3, 8, 2],
        [3, 3, 6, 1],
        [1, 1, 1, 4]]])

In [176]:
data = np.array([[1], [2], [3]])

In [177]:
data

array([[1],
       [2],
       [3]])

In [178]:
np.squeeze(data)

array([1, 2, 3])

In [179]:
data

array([[1],
       [2],
       [3]])

In [180]:
np.repeat(data, 2)

array([1, 1, 2, 2, 3, 3])

In [181]:
np.repeat(data, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [183]:
np.roll(data, 2)

array([[2],
       [3],
       [1]])

In [185]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [186]:
#Numpy - Binary Operations.

In [187]:
arr1 = np.random.randint(1,10, (3,4))
arr2 = np.random.randint(1,10, (3,4))

In [188]:
arr1


array([[4, 9, 8, 2],
       [6, 1, 8, 9],
       [5, 6, 8, 1]])

In [189]:
arr2

array([[6, 1, 8, 1],
       [7, 1, 7, 9],
       [2, 6, 9, 4]])

In [190]:
arr1 + arr2

array([[10, 10, 16,  3],
       [13,  2, 15, 18],
       [ 7, 12, 17,  5]])

In [191]:
arr1 * arr2

array([[24,  9, 64,  2],
       [42,  1, 56, 81],
       [10, 36, 72,  4]])

In [192]:
arr1 / arr2

array([[0.66666667, 9.        , 1.        , 2.        ],
       [0.85714286, 1.        , 1.14285714, 1.        ],
       [2.5       , 1.        , 0.88888889, 0.25      ]])

In [193]:
arr1 - arr2

array([[-2,  8,  0,  1],
       [-1,  0,  1,  0],
       [ 3,  0, -1, -3]])

In [194]:
arr1 **arr2

array([[     4096,         9,  16777216,         2],
       [   279936,         1,   2097152, 387420489],
       [       25,     46656, 134217728,         1]])

In [195]:
~arr1

array([[ -5, -10,  -9,  -3],
       [ -7,  -2,  -9, -10],
       [ -6,  -7,  -9,  -2]])

In [196]:
arr1 > arr2

array([[False,  True, False,  True],
       [False, False,  True, False],
       [ True, False, False, False]])

In [197]:
arr1[arr1 > arr2]

array([9, 2, 8, 5])

In [198]:
arr2[arr1 > arr2]

array([1, 1, 7, 2])

In [199]:
#Numpy - String Functions

In [200]:
arr = np.array(['sudh', 'kumar'])

In [201]:
arr

array(['sudh', 'kumar'], dtype='<U5')

In [202]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [203]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [204]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [205]:
#Numpy - Mathematical Functions.

In [206]:
arr1

array([[4, 9, 8, 2],
       [6, 1, 8, 9],
       [5, 6, 8, 1]])

In [207]:
np.sin(arr1)

array([[-0.7568025 ,  0.41211849,  0.98935825,  0.90929743],
       [-0.2794155 ,  0.84147098,  0.98935825,  0.41211849],
       [-0.95892427, -0.2794155 ,  0.98935825,  0.84147098]])

In [208]:
np.cos(arr1)

array([[-0.65364362, -0.91113026, -0.14550003, -0.41614684],
       [ 0.96017029,  0.54030231, -0.14550003, -0.91113026],
       [ 0.28366219,  0.96017029, -0.14550003,  0.54030231]])

In [209]:
np.tan(arr1)

array([[ 1.15782128, -0.45231566, -6.79971146, -2.18503986],
       [-0.29100619,  1.55740772, -6.79971146, -0.45231566],
       [-3.38051501, -0.29100619, -6.79971146,  1.55740772]])

In [210]:
np.log(arr1)

array([[1.38629436, 2.19722458, 2.07944154, 0.69314718],
       [1.79175947, 0.        , 2.07944154, 2.19722458],
       [1.60943791, 1.79175947, 2.07944154, 0.        ]])

In [211]:
np.exp(arr1)

array([[5.45981500e+01, 8.10308393e+03, 2.98095799e+03, 7.38905610e+00],
       [4.03428793e+02, 2.71828183e+00, 2.98095799e+03, 8.10308393e+03],
       [1.48413159e+02, 4.03428793e+02, 2.98095799e+03, 2.71828183e+00]])

In [212]:
np.power(arr1, 2)

array([[16, 81, 64,  4],
       [36,  1, 64, 81],
       [25, 36, 64,  1]], dtype=int32)

In [213]:
np.mean(arr1)

5.583333333333333

In [214]:
np.median(arr1)

6.0

In [215]:
np.std(arr1)

2.8710721961587025

In [216]:
np.var(arr1)

8.243055555555555

In [217]:
np.min(arr1)

1

In [218]:
np.max(arr1)

9

In [219]:
#Numpy - Arithmetic Operations.

In [220]:
arr1

array([[4, 9, 8, 2],
       [6, 1, 8, 9],
       [5, 6, 8, 1]])

In [221]:
arr2

array([[6, 1, 8, 1],
       [7, 1, 7, 9],
       [2, 6, 9, 4]])

In [222]:
arr1 - arr2

array([[-2,  8,  0,  1],
       [-1,  0,  1,  0],
       [ 3,  0, -1, -3]])

In [224]:
np.subtract(arr1, arr2)

array([[-2,  8,  0,  1],
       [-1,  0,  1,  0],
       [ 3,  0, -1, -3]])

In [225]:
np.multiply(arr1, arr2)

array([[24,  9, 64,  2],
       [42,  1, 56, 81],
       [10, 36, 72,  4]])

In [226]:
np.mod(arr1, arr2)

array([[4, 0, 0, 0],
       [6, 0, 1, 0],
       [1, 0, 8, 1]])

In [227]:
np.power(arr1, arr2)

array([[     4096,         9,  16777216,         2],
       [   279936,         1,   2097152, 387420489],
       [       25,     46656, 134217728,         1]])

In [229]:
np.sqrt(arr1)

array([[2.        , 3.        , 2.82842712, 1.41421356],
       [2.44948974, 1.        , 2.82842712, 3.        ],
       [2.23606798, 2.44948974, 2.82842712, 1.        ]])

In [230]:
#Statistical Functions.

In [231]:
arr1

array([[4, 9, 8, 2],
       [6, 1, 8, 9],
       [5, 6, 8, 1]])

In [232]:
np.mean(arr1)

5.583333333333333

In [233]:
np.std(arr1)

2.8710721961587025

## PART 4

In [234]:
##Sort, Search & Counting functions.

In [235]:
import numpy as np

In [238]:
arr = np.array([4,2,8,5,3,9,12,56])

In [239]:
arr

array([ 4,  2,  8,  5,  3,  9, 12, 56])

In [240]:
np.sort(arr)

array([ 2,  3,  4,  5,  8,  9, 12, 56])

In [241]:
np.searchsorted(arr, 6)

5

In [242]:
arr1 = np.array([0,324,645,65,6,6,0,0,0,234])

In [243]:
np.count_nonzero(arr1)

6

In [245]:
len(arr1)

10

In [249]:
np.where(arr1 > 0)

(array([1, 2, 3, 4, 5, 9], dtype=int64),)

In [252]:
np.extract(arr1>2, arr1)

array([324, 645,  65,   6,   6, 234])

In [253]:
## Numpy - Byte Swapping

In [254]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [257]:
arr.byteswap(True)

array([ 67108864,  33554432, 134217728,  83886080,  50331648, 150994944,
       201326592, 939524096])

In [258]:
arr

array([ 67108864,  33554432, 134217728,  83886080,  50331648, 150994944,
       201326592, 939524096])

In [259]:
#Numpy - Copies & Views

In [260]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [261]:
a = np.copy(arr1)

In [262]:
b = arr1.view()

In [263]:
b

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [264]:
b[0] = 234

In [265]:
b

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [266]:
arr1

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [267]:
##Numpy - Matrix Library

In [269]:
import numpy.matlib as nm

In [270]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [271]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [272]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [273]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [275]:
np.diag([4,3,4,5])

array([[4, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [276]:
#Numpy - Linear Algebra

In [278]:
arr1 = np.random.randint([[2,3], [4,5]])

In [279]:
arr2 = np.random.randint([[5,3], [2,5]])

In [280]:
arr1

array([[0, 2],
       [2, 3]])

In [281]:
arr2

array([[2, 0],
       [0, 1]])

In [282]:
np.dot(arr1, arr2)

array([[0, 2],
       [4, 3]])

In [284]:
arr1@arr2

array([[0, 2],
       [4, 3]])

In [285]:
a = np.array([2,4,5,6])
threshold = 2

In [287]:
a[a>threshold] = 0

In [288]:
a

array([2, 0, 0, 0])

In [289]:
np.argsort()

AttributeError: module 'numpy' has no attribute 'distinct'